general:
  project_name: Pascal_VOC_2012_Demo
  logs_dir: logs
  saved_models_dir: saved_models

train_parameters:
  batch_size: 64
  training_epochs: 10000
  optimizer: adam
  initial_learning: 0.001
  learning_rate_scheduler: reducelronplateau

dataset:
  name: Pascal_VOC_2012
  class_names: [aeroplane,bicycle,bird,boat,bottle,bus,car,cat,chair,cow,diningtable,dog,horse,motorbike,person,pottedplant,sheep,sofa,train,tvmonitor]
  training_path: C:/stmicroelectronics2022/DATASETS/voc_2012/train
  validation_path: C:/stmicroelectronics2022/DATASETS/voc_2012/valid
  test_path: 

pre_processing:
  rescaling: {scale : 127.5, offset : -1}
  resizing: bilinear
  aspect_ratio: False
  color_mode: rgb

post_processing:
  confidence_thresh: 0.01
  NMS_thresh: 0.5
  IoU_eval_thresh: 0.4

model:
  model_type: {name : mobilenet, version : v1, alpha : 0.25} 
  input_shape: [192,192, 3]
  model_path: sd_mobilenet_v1_0.25_192/ssd_mobilenet_v1_025_192_int8.tflite

quantization:
  quantize: True
  evaluate: True
  quantizer: TFlite_converter
  quantization_type: PTQ
  quantization_input_type: uint8
  quantization_output_type: float
  export_dir: quantized_models

stm32ai:
  optimization: balanced
  footprints_on_target: STM32H747I-DISCO
  path_to_stm32ai: C:/stmicroelectronics2022/cube_ai/windows/stm32ai.exe
  
mlflow:
  uri: ./mlruns

hydra:
  run:
    dir: outputs/${now:%Y_%m_%d_%H_%M_%S}
